# ==========================================================
# Christina's World - 核心配置文件
# 基于 So Simple Theme 官方示例修改
# ==========================================================
title: Christina's World
description: 我的数字花园，记录小说、摄影与技术。
locale: zh-CN
url: "https://christinayxr.com"
baseurl: ""

remote_theme: mmistakes/so-simple-theme@3.2.0
skin: /assets/css/skins/default.css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 10
search_full_content: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true
      sidebar:
        nav: "main"

author:
  name: Christina
  email: xinran.yang97@qq.com
  links:
    - title: GitHub
      url: https://github.com/ChristinaYang233333
      icon: fab fa-github-square

footer_links:
  - title: 隐私政策
    url: /privacy/
  - title: 服务条款
    url: /terms/
    icon: fas fa-rss-square
