# -----------------------
# 核心设置
# -----------------------
title: Christina's World
description: 我的数字花园，记录小说、摄影与技术。
url: "https://christinayang233333.github.io" 
baseurl: ""  # 主站必须留空

# -----------------------
# 主题设置
# -----------------------
remote_theme: mmistakes/so-simple-theme
skin: /assets/css/skins/default.css # 你也可以换成 dark.css 或 solarized-light.css


# -----------------------
# 底部链接 (隐私条款)
# -----------------------
footer_links:
  - title: 隐私政策
    url: /privacy/
  - title: 服务条款
    url: /terms/

# -----------------------
# 插件与构建设置
# -----------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

# -----------------------
# 其他设置
# -----------------------
search: true           # 开启搜索功能
read_time: true        # 显示阅读时间
words_per_minute: 200
